server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/contacts.jhinesconsulting.com/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat