spring:
  datasource:
    url: jdbc:mysql://mysql:3306/jhinesconsulting?useSSL=false
    username: ${JHC_DB_USER}
    password: ${JHC_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JHC_GMAIL_ADDRESS}
    password: ${JHC_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            trust: smtp.gmail.com

logging:
  level:
    org.springframework: INFO
    com.hines.james: INFO